services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  BirdCode\BcSimplerate\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  BirdCode\BcSimplerate\Utility\TemplateLayout:
    public: true  

  BirdCode\BcSimplerate\Hooks\ItemsProcFunc:
    public: true    